name: Deploy FastAPI to Azure Web App

on:
  push:
    branches:
      - main  # Trigger on push to main branch

env:
  AZURE_WEBAPP_NAME: myFastAPIApp
  AZURE_RESOURCE_GROUP: myResourceGroup
  AZURE_PLAN_NAME: myAppServicePlan
  PYTHON_VERSION: "3.9"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install Dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        pip install fastapi uvicorn gunicorn
        pip freeze > requirements.txt

    - name: Create Startup Script
      run: |
        echo "gunicorn -w 4 -k uvicorn.workers.UvicornWorker app:app" > startup.sh
        chmod +x startup.sh

    - name: Create ZIP Package
      run: |
        zip -r fastapi-app.zip * -x "venv/*"
